### ISSUE TITLE
Could you provide script for running word-level QE task?

### ISSUE THREAD

**Issue by MottoX** [sheffieldnlp/deepQuest#6]
Hi, thanks for creating deepQuest. I was trying to run your framework on WMT-18 word-level QE task. However, there is no shell script for word-level prediction available. It will be really great if you can provide a script to easily run the framework on WMT word-level QE task.

**Comment by fredblain** [comment]
Hi @MottoX,
to trained a word-level QE model, the process is pretty much the same as for sentence-level.  
If you haven't done it since you opened this issue, I invite you to have a look at the this [training script](https://github.com/sheffieldnlp/deepQuest/blob/master/configs/train-test-sentQEbRNN.sh) from Julia, as a starting point. The first mandatory change to make is to set the 'model_type' variable with one of the word-level QE model supported by deepQuest (e.g. 'EncWord' for the BiRNN model).
Please let me know.
Cheers,

**Comment by MottoX** [comment]
Hi @fredblain ,
Thanks for you reply!
